[2025-01-06T17:10:40.321+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-06T17:10:40.347+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_dag.clearing_table_task manual__2025-01-06T17:10:33.683938+00:00 [queued]>
[2025-01-06T17:10:40.367+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_dag.clearing_table_task manual__2025-01-06T17:10:33.683938+00:00 [queued]>
[2025-01-06T17:10:40.369+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-06T17:10:40.392+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): clearing_table_task> on 2025-01-06 17:10:33.683938+00:00
[2025-01-06T17:10:40.400+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=300) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-06T17:10:40.402+0000] {standard_task_runner.py:72} INFO - Started process 301 to run task
[2025-01-06T17:10:40.404+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_dag', 'clearing_table_task', 'manual__2025-01-06T17:10:33.683938+00:00', '--job-id', '832', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_dag.py', '--cfg-path', '/tmp/tmpvh7sang2']
[2025-01-06T17:10:40.406+0000] {standard_task_runner.py:105} INFO - Job 832: Subtask clearing_table_task
[2025-01-06T17:10:40.481+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_dag.clearing_table_task manual__2025-01-06T17:10:33.683938+00:00 [running]> on host 97bbb29a7501
[2025-01-06T17:10:40.638+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_dag' AIRFLOW_CTX_TASK_ID='clearing_table_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T17:10:33.683938+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-06T17:10:33.683938+00:00'
[2025-01-06T17:10:40.640+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-06T17:10:40.662+0000] {sql.py:278} INFO - Executing: TRUNCATE STG.adv;
[2025-01-06T17:10:40.675+0000] {base.py:84} INFO - Retrieving connection 'pg_connect'
[2025-01-06T17:10:40.689+0000] {base.py:84} INFO - Retrieving connection 'pg_connect'
[2025-01-06T17:10:40.696+0000] {sql.py:553} INFO - Running statement: TRUNCATE STG.adv;, parameters: None
[2025-01-06T17:10:40.722+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-06T17:10:40.723+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=kaggle_dag, task_id=clearing_table_task, run_id=manual__2025-01-06T17:10:33.683938+00:00, execution_date=20250106T171033, start_date=20250106T171040, end_date=20250106T171040
[2025-01-06T17:10:40.779+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-06T17:10:40.827+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-06T17:10:40.832+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
