[2025-01-06T17:09:25.499+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-06T17:09:25.528+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_dag.load_data manual__2025-01-06T17:09:10.884749+00:00 [queued]>
[2025-01-06T17:09:25.547+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_dag.load_data manual__2025-01-06T17:09:10.884749+00:00 [queued]>
[2025-01-06T17:09:25.549+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-06T17:09:25.579+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data> on 2025-01-06 17:09:10.884749+00:00
[2025-01-06T17:09:25.589+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=272) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-06T17:09:25.592+0000] {standard_task_runner.py:72} INFO - Started process 273 to run task
[2025-01-06T17:09:25.592+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_dag', 'load_data', 'manual__2025-01-06T17:09:10.884749+00:00', '--job-id', '828', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_dag.py', '--cfg-path', '/tmp/tmphchzmt1v']
[2025-01-06T17:09:25.594+0000] {standard_task_runner.py:105} INFO - Job 828: Subtask load_data
[2025-01-06T17:09:25.666+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_dag.load_data manual__2025-01-06T17:09:10.884749+00:00 [running]> on host 97bbb29a7501
[2025-01-06T17:09:25.854+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T17:09:10.884749+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-06T17:09:10.884749+00:00'
[2025-01-06T17:09:25.857+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-06T17:09:25.913+0000] {base.py:84} INFO - Retrieving connection 'pg_connect'
[2025-01-06T17:09:26.271+0000] {kaggle_dag.py:47} INFO - Данные вставились в БД
[2025-01-06T17:09:26.273+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-06T17:09:26.292+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-06T17:09:26.293+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=kaggle_dag, task_id=load_data, run_id=manual__2025-01-06T17:09:10.884749+00:00, execution_date=20250106T170910, start_date=20250106T170925, end_date=20250106T170926
[2025-01-06T17:09:26.372+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-06T17:09:26.415+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-06T17:09:26.421+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
