[2025-01-06T10:34:20.952+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-06T10:34:20.990+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_dag.clearing_table_task manual__2025-01-06T10:34:14.497188+00:00 [queued]>
[2025-01-06T10:34:21.011+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_dag.clearing_table_task manual__2025-01-06T10:34:14.497188+00:00 [queued]>
[2025-01-06T10:34:21.012+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-06T10:34:21.041+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): clearing_table_task> on 2025-01-06 10:34:14.497188+00:00
[2025-01-06T10:34:21.052+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=438) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-06T10:34:21.055+0000] {standard_task_runner.py:72} INFO - Started process 439 to run task
[2025-01-06T10:34:21.054+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_dag', 'clearing_table_task', 'manual__2025-01-06T10:34:14.497188+00:00', '--job-id', '802', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_dag.py', '--cfg-path', '/tmp/tmp4pbl5qpg']
[2025-01-06T10:34:21.057+0000] {standard_task_runner.py:105} INFO - Job 802: Subtask clearing_table_task
[2025-01-06T10:34:21.140+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_dag.clearing_table_task manual__2025-01-06T10:34:14.497188+00:00 [running]> on host 4f9b54363226
[2025-01-06T10:34:21.335+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_dag' AIRFLOW_CTX_TASK_ID='clearing_table_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T10:34:14.497188+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-06T10:34:14.497188+00:00'
[2025-01-06T10:34:21.338+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-06T10:34:21.381+0000] {sql.py:278} INFO - Executing: TRUNCATE STG.adv;
[2025-01-06T10:34:21.403+0000] {base.py:84} INFO - Retrieving connection 'pg_connect'
[2025-01-06T10:34:21.428+0000] {base.py:84} INFO - Retrieving connection 'pg_connect'
[2025-01-06T10:34:21.436+0000] {sql.py:553} INFO - Running statement: TRUNCATE STG.adv;, parameters: None
[2025-01-06T10:34:21.484+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-06T10:34:21.485+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=kaggle_dag, task_id=clearing_table_task, run_id=manual__2025-01-06T10:34:14.497188+00:00, execution_date=20250106T103414, start_date=20250106T103420, end_date=20250106T103421
[2025-01-06T10:34:21.558+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-06T10:34:21.643+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-06T10:34:21.649+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
