[2025-01-06T17:36:59.400+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-06T17:36:59.426+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_dag.clearing_table_task manual__2025-01-06T17:36:52.905070+00:00 [queued]>
[2025-01-06T17:36:59.434+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_dag.clearing_table_task manual__2025-01-06T17:36:52.905070+00:00 [queued]>
[2025-01-06T17:36:59.435+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-06T17:36:59.450+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): clearing_table_task> on 2025-01-06 17:36:52.905070+00:00
[2025-01-06T17:36:59.455+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=134) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-06T17:36:59.456+0000] {standard_task_runner.py:72} INFO - Started process 135 to run task
[2025-01-06T17:36:59.457+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_dag', 'clearing_table_task', 'manual__2025-01-06T17:36:52.905070+00:00', '--job-id', '848', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_dag.py', '--cfg-path', '/tmp/tmp1axs0fp2']
[2025-01-06T17:36:59.458+0000] {standard_task_runner.py:105} INFO - Job 848: Subtask clearing_table_task
[2025-01-06T17:36:59.501+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_dag.clearing_table_task manual__2025-01-06T17:36:52.905070+00:00 [running]> on host f560492d2669
[2025-01-06T17:36:59.593+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_dag' AIRFLOW_CTX_TASK_ID='clearing_table_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T17:36:52.905070+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-06T17:36:52.905070+00:00'
[2025-01-06T17:36:59.594+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-06T17:36:59.607+0000] {sql.py:278} INFO - Executing: TRUNCATE STG.adv;
[2025-01-06T17:36:59.615+0000] {base.py:84} INFO - Retrieving connection 'pg_connect'
[2025-01-06T17:36:59.622+0000] {base.py:84} INFO - Retrieving connection 'pg_connect'
[2025-01-06T17:36:59.625+0000] {sql.py:553} INFO - Running statement: TRUNCATE STG.adv;, parameters: None
[2025-01-06T17:36:59.638+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-06T17:36:59.638+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=kaggle_dag, task_id=clearing_table_task, run_id=manual__2025-01-06T17:36:52.905070+00:00, execution_date=20250106T173652, start_date=20250106T173659, end_date=20250106T173659
[2025-01-06T17:36:59.671+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-06T17:36:59.726+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-06T17:36:59.730+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
