[2025-01-06T08:51:04.293+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-06T08:51:04.335+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_dag.load_data manual__2025-01-06T08:50:50.130887+00:00 [queued]>
[2025-01-06T08:51:04.357+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_dag.load_data manual__2025-01-06T08:50:50.130887+00:00 [queued]>
[2025-01-06T08:51:04.358+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-06T08:51:04.389+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data> on 2025-01-06 08:50:50.130887+00:00
[2025-01-06T08:51:04.400+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=102) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-06T08:51:04.403+0000] {standard_task_runner.py:72} INFO - Started process 103 to run task
[2025-01-06T08:51:04.404+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_dag', 'load_data', 'manual__2025-01-06T08:50:50.130887+00:00', '--job-id', '773', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_dag.py', '--cfg-path', '/tmp/tmp8byeliah']
[2025-01-06T08:51:04.407+0000] {standard_task_runner.py:105} INFO - Job 773: Subtask load_data
[2025-01-06T08:51:04.504+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_dag.load_data manual__2025-01-06T08:50:50.130887+00:00 [running]> on host ffbd28c5220f
[2025-01-06T08:51:04.725+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T08:50:50.130887+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-06T08:50:50.130887+00:00'
[2025-01-06T08:51:04.727+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-06T08:51:04.787+0000] {base.py:84} INFO - Retrieving connection 'pg_connect'
[2025-01-06T08:51:05.263+0000] {kaggle_dag.py:48} INFO - Данные вставились в БД
[2025-01-06T08:51:05.265+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-06T08:51:05.287+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-06T08:51:05.288+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=kaggle_dag, task_id=load_data, run_id=manual__2025-01-06T08:50:50.130887+00:00, execution_date=20250106T085050, start_date=20250106T085104, end_date=20250106T085105
[2025-01-06T08:51:05.347+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-06T08:51:05.409+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-06T08:51:05.415+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
