[2025-01-06T17:08:46.798+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-06T17:08:46.825+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_dag.clearing_table_task manual__2025-01-06T17:08:39.941636+00:00 [queued]>
[2025-01-06T17:08:46.840+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_dag.clearing_table_task manual__2025-01-06T17:08:39.941636+00:00 [queued]>
[2025-01-06T17:08:46.842+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-06T17:08:46.871+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): clearing_table_task> on 2025-01-06 17:08:39.941636+00:00
[2025-01-06T17:08:46.881+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=225) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-06T17:08:46.884+0000] {standard_task_runner.py:72} INFO - Started process 226 to run task
[2025-01-06T17:08:46.884+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_dag', 'clearing_table_task', 'manual__2025-01-06T17:08:39.941636+00:00', '--job-id', '818', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_dag.py', '--cfg-path', '/tmp/tmpfgm2392j']
[2025-01-06T17:08:46.887+0000] {standard_task_runner.py:105} INFO - Job 818: Subtask clearing_table_task
[2025-01-06T17:08:46.968+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_dag.clearing_table_task manual__2025-01-06T17:08:39.941636+00:00 [running]> on host 97bbb29a7501
[2025-01-06T17:08:47.133+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_dag' AIRFLOW_CTX_TASK_ID='clearing_table_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T17:08:39.941636+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-06T17:08:39.941636+00:00'
[2025-01-06T17:08:47.136+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-06T17:08:47.168+0000] {sql.py:278} INFO - Executing: TRUNCATE STG.adv;
[2025-01-06T17:08:47.184+0000] {base.py:84} INFO - Retrieving connection 'pg_connect'
[2025-01-06T17:08:47.195+0000] {base.py:84} INFO - Retrieving connection 'pg_connect'
[2025-01-06T17:08:47.202+0000] {sql.py:553} INFO - Running statement: TRUNCATE STG.adv;, parameters: None
[2025-01-06T17:08:47.230+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-06T17:08:47.231+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=kaggle_dag, task_id=clearing_table_task, run_id=manual__2025-01-06T17:08:39.941636+00:00, execution_date=20250106T170839, start_date=20250106T170846, end_date=20250106T170847
[2025-01-06T17:08:47.264+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-06T17:08:47.314+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-06T17:08:47.320+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
