[2025-01-06T17:08:53.946+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-06T17:08:53.978+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_dag.load_data manual__2025-01-06T17:08:39.941636+00:00 [queued]>
[2025-01-06T17:08:53.997+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_dag.load_data manual__2025-01-06T17:08:39.941636+00:00 [queued]>
[2025-01-06T17:08:53.999+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-06T17:08:54.039+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data> on 2025-01-06 17:08:39.941636+00:00
[2025-01-06T17:08:54.050+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=238) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-06T17:08:54.053+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_dag', 'load_data', 'manual__2025-01-06T17:08:39.941636+00:00', '--job-id', '821', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_dag.py', '--cfg-path', '/tmp/tmpgwsxorfz']
[2025-01-06T17:08:54.055+0000] {standard_task_runner.py:72} INFO - Started process 239 to run task
[2025-01-06T17:08:54.055+0000] {standard_task_runner.py:105} INFO - Job 821: Subtask load_data
[2025-01-06T17:08:54.368+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_dag.load_data manual__2025-01-06T17:08:39.941636+00:00 [running]> on host 97bbb29a7501
[2025-01-06T17:08:54.592+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T17:08:39.941636+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-06T17:08:39.941636+00:00'
[2025-01-06T17:08:54.596+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-06T17:08:54.647+0000] {base.py:84} INFO - Retrieving connection 'pg_connect'
[2025-01-06T17:08:55.028+0000] {kaggle_dag.py:47} INFO - Данные вставились в БД
[2025-01-06T17:08:55.030+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-06T17:08:55.049+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-06T17:08:55.050+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=kaggle_dag, task_id=load_data, run_id=manual__2025-01-06T17:08:39.941636+00:00, execution_date=20250106T170839, start_date=20250106T170853, end_date=20250106T170855
[2025-01-06T17:08:55.119+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-06T17:08:55.167+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-06T17:08:55.173+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
