[2025-01-06T19:18:36.132+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-06T19:18:36.178+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_dag.load_data manual__2025-01-06T19:18:16.983417+00:00 [queued]>
[2025-01-06T19:18:36.198+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_dag.load_data manual__2025-01-06T19:18:16.983417+00:00 [queued]>
[2025-01-06T19:18:36.200+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-06T19:18:36.233+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data> on 2025-01-06 19:18:16.983417+00:00
[2025-01-06T19:18:36.243+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=118) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-06T19:18:36.249+0000] {standard_task_runner.py:72} INFO - Started process 119 to run task
[2025-01-06T19:18:36.247+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_dag', 'load_data', 'manual__2025-01-06T19:18:16.983417+00:00', '--job-id', '862', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_dag.py', '--cfg-path', '/tmp/tmp_0vcjad0']
[2025-01-06T19:18:36.250+0000] {standard_task_runner.py:105} INFO - Job 862: Subtask load_data
[2025-01-06T19:18:36.356+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_dag.load_data manual__2025-01-06T19:18:16.983417+00:00 [running]> on host b5c0ace8ab2f
[2025-01-06T19:18:36.573+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T19:18:16.983417+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-06T19:18:16.983417+00:00'
[2025-01-06T19:18:36.576+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-06T19:18:36.621+0000] {base.py:84} INFO - Retrieving connection 'pg_connect'
[2025-01-06T19:18:37.006+0000] {kaggle_dag.py:51} INFO - Данные вставились в БД
[2025-01-06T19:18:37.009+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-06T19:18:37.031+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-06T19:18:37.032+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=kaggle_dag, task_id=load_data, run_id=manual__2025-01-06T19:18:16.983417+00:00, execution_date=20250106T191816, start_date=20250106T191836, end_date=20250106T191837
[2025-01-06T19:18:37.070+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-06T19:18:37.122+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-06T19:18:37.129+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
