[2025-01-05T22:12:54.147+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-05T22:12:54.186+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_dag.load_data manual__2025-01-05T22:12:39.202851+00:00 [queued]>
[2025-01-05T22:12:54.219+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_dag.load_data manual__2025-01-05T22:12:39.202851+00:00 [queued]>
[2025-01-05T22:12:54.223+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-05T22:12:54.260+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data> on 2025-01-05 22:12:39.202851+00:00
[2025-01-05T22:12:54.271+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=146) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-05T22:12:54.274+0000] {standard_task_runner.py:72} INFO - Started process 147 to run task
[2025-01-05T22:12:54.276+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_dag', 'load_data', 'manual__2025-01-05T22:12:39.202851+00:00', '--job-id', '765', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_dag.py', '--cfg-path', '/tmp/tmp00pl2j6b']
[2025-01-05T22:12:54.281+0000] {standard_task_runner.py:105} INFO - Job 765: Subtask load_data
[2025-01-05T22:12:54.389+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_dag.load_data manual__2025-01-05T22:12:39.202851+00:00 [running]> on host ffbd28c5220f
[2025-01-05T22:12:54.576+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-05T22:12:39.202851+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-05T22:12:39.202851+00:00'
[2025-01-05T22:12:54.578+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-05T22:12:54.628+0000] {base.py:84} INFO - Retrieving connection 'pg_connect'
[2025-01-05T22:12:54.954+0000] {kaggle_dag.py:48} INFO - Данные вставились в БД
[2025-01-05T22:12:54.955+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-05T22:12:54.975+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-05T22:12:54.976+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=kaggle_dag, task_id=load_data, run_id=manual__2025-01-05T22:12:39.202851+00:00, execution_date=20250105T221239, start_date=20250105T221254, end_date=20250105T221254
[2025-01-05T22:12:55.021+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-05T22:12:55.062+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-05T22:12:55.067+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
