[2025-01-05T22:12:22.178+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-05T22:12:22.219+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_dag.load_data manual__2025-01-05T22:12:07.663152+00:00 [queued]>
[2025-01-05T22:12:22.243+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_dag.load_data manual__2025-01-05T22:12:07.663152+00:00 [queued]>
[2025-01-05T22:12:22.245+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-05T22:12:22.275+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data> on 2025-01-05 22:12:07.663152+00:00
[2025-01-05T22:12:22.284+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=116) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-05T22:12:22.288+0000] {standard_task_runner.py:72} INFO - Started process 117 to run task
[2025-01-05T22:12:22.289+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_dag', 'load_data', 'manual__2025-01-05T22:12:07.663152+00:00', '--job-id', '759', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_dag.py', '--cfg-path', '/tmp/tmpn0orh5iw']
[2025-01-05T22:12:22.292+0000] {standard_task_runner.py:105} INFO - Job 759: Subtask load_data
[2025-01-05T22:12:22.370+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_dag.load_data manual__2025-01-05T22:12:07.663152+00:00 [running]> on host ffbd28c5220f
[2025-01-05T22:12:22.528+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-05T22:12:07.663152+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-05T22:12:07.663152+00:00'
[2025-01-05T22:12:22.531+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-05T22:12:22.579+0000] {base.py:84} INFO - Retrieving connection 'pg_connect'
[2025-01-05T22:12:22.941+0000] {kaggle_dag.py:48} INFO - Данные вставились в БД
[2025-01-05T22:12:22.944+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-05T22:12:22.964+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-05T22:12:22.965+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=kaggle_dag, task_id=load_data, run_id=manual__2025-01-05T22:12:07.663152+00:00, execution_date=20250105T221207, start_date=20250105T221222, end_date=20250105T221222
[2025-01-05T22:12:23.029+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-05T22:12:23.084+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-05T22:12:23.090+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
