[2025-01-06T17:01:10.344+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-06T17:01:10.379+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_dag.clearing_table_task manual__2025-01-06T17:01:03.433436+00:00 [queued]>
[2025-01-06T17:01:10.399+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_dag.clearing_table_task manual__2025-01-06T17:01:03.433436+00:00 [queued]>
[2025-01-06T17:01:10.400+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-06T17:01:10.430+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): clearing_table_task> on 2025-01-06 17:01:03.433436+00:00
[2025-01-06T17:01:10.439+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=107) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-06T17:01:10.442+0000] {standard_task_runner.py:72} INFO - Started process 108 to run task
[2025-01-06T17:01:10.442+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_dag', 'clearing_table_task', 'manual__2025-01-06T17:01:03.433436+00:00', '--job-id', '811', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_dag.py', '--cfg-path', '/tmp/tmpavc0wkrj']
[2025-01-06T17:01:10.445+0000] {standard_task_runner.py:105} INFO - Job 811: Subtask clearing_table_task
[2025-01-06T17:01:10.527+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_dag.clearing_table_task manual__2025-01-06T17:01:03.433436+00:00 [running]> on host 97bbb29a7501
[2025-01-06T17:01:10.691+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_dag' AIRFLOW_CTX_TASK_ID='clearing_table_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T17:01:03.433436+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-06T17:01:03.433436+00:00'
[2025-01-06T17:01:10.694+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-06T17:01:10.717+0000] {sql.py:278} INFO - Executing: TRUNCATE STG.adv;
[2025-01-06T17:01:10.732+0000] {base.py:84} INFO - Retrieving connection 'pg_connect'
[2025-01-06T17:01:10.746+0000] {base.py:84} INFO - Retrieving connection 'pg_connect'
[2025-01-06T17:01:10.754+0000] {sql.py:553} INFO - Running statement: TRUNCATE STG.adv;, parameters: None
[2025-01-06T17:01:10.784+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-06T17:01:10.785+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=kaggle_dag, task_id=clearing_table_task, run_id=manual__2025-01-06T17:01:03.433436+00:00, execution_date=20250106T170103, start_date=20250106T170110, end_date=20250106T170110
[2025-01-06T17:01:10.820+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-06T17:01:10.872+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-06T17:01:10.878+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
